### ISSUE TITLE
Pulling from Modded Dedicated Storages

### ISSUE THREAD

**Issue by DracoFlame90** [VoidArkMods/QoLPlus#47]
Currently using the mod Klinger Additions, which adds new wood, stone and metal dedicated storages, and can't pull any of the resources that are within the storages. Can still auto craft from them in my inventory, or structures that allow for auto crafting. But any of the modded structures which don't have auto craft support also can't pull from the dedicated storages. I did go into GCM and test with a Tek Dedicated Storage and it works with that, just not with the modded ones. I'm not sure if this is something that you can fix on your end, or if I need to talk with the creator of Klinger Additions

**Comment by VoidArkMods** [comment]
Hello!
This issue looks like a duplicate of https://github.com/VoidArkMods/QoLPlus/issues/34, where I already answered regarding some of your concerns. I will add S+ dedicated storages at some point, but really want to do it the right way to enable remove crafting and all the new features from ASA.

**Comment by DracoFlame90** [comment]
Sorry, but my OP is not a copy of #34 which is asking about refrigerated storage. My question is if it is possible to allow pulling from other modded dedicated storage.

**Comment by DracoFlame90** [comment]
> > Sorry, but my OP is not a copy of #34 which is asking about refrigerated storage.
> > My question is if it is possible to allow pulling from other modded dedicated storage. Interaction between this mod, and another mod that adds in different types of Dedicated Storage.
> 
> Except it is because that's also mentioned in that ticket.

Ah then my apologies, saw that the first post was asking about refrigerated storage, not that Klingers was mentioned in a later post.

**Comment by VoidArkMods** [comment]
QoL+ Dedicated storages are now available and pulling from/to them (and vanilla dedicated storages) has been fixed. However, this may or may not have fixed other dedicated storages from other mods.

**Comment by zerafox** [comment]
> QoL+ Dedicated storages are now available and pulling from/to them (and vanilla dedicated storages) has been fixed. However, this may or may not have fixed other dedicated storages from other mods.

This has not resolved pulling from other Dedi systems, just so you're aware.
